name: GraalVM Native Image builds
on: [ push, pull_request, workflow_dispatch ]
jobs:
  build:
    name: Example on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-14, windows-2022, ubuntu-20.04 ]
    steps:
      - uses: actions/checkout@v4

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - name: Build with maven
        run: mvn -Pnative package

      - name: list files
        run: ls -la target

      - name: Upload native image
        uses: actions/upload-artifact@v4
        with:
          name: example-${{ matrix.os }}
          path: target/event-application-example